version: "3.7"
services:
  db:
    image: mysql:latest
    container_name: spring-boot-three-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=product
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
volumes:
  db:

